### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by telegrambotdev** [subins2000/WebDrop#3]
Need folder transfer feature too.just like we can upload folders on `fex.net` website.
as like can we share the folders too ?

**Comment by subins2000** [comment]
Added it. Each files in the folder will be sent separately though and on the receiving side, each file has to be download each. Perhaps downloading everything as a Zip file should be implemented. What do you think ?

There are libraries to make zip files in JS apparently ! https://stuk.github.io/jszip/

**Comment by subins2000** [comment]
Both files and folder can't be uploaded from same input element : https://stackoverflow.com/q/40786685/1372424

So, will be removing folder upload from the button, but you can still drag over folders and upload.
